import assert from "node:assert/strict";
import test from "node:test";

import {
  fetchWithRetry,
  refreshAccessToken,
  retryReasonForResponse,
  truncateText,
} from "../scripts/generate-exercise-svg.mjs";

const cloudFrontBlockHtml = `<!DOCTYPE html>
<html>
  <body>
    <h1>403 ERROR</h1>
    <h2>The request could not be satisfied.</h2>
    Request blocked.
    Generated by cloudfront (CloudFront)
  </body>
</html>`;

function jsonResponse(body, init = {}) {
  return new Response(JSON.stringify(body), {
    headers: { "Content-Type": "application/json" },
    ...init,
  });
}

test("CloudFront-like 403 responses are retried when enabled", async () => {
  let calls = 0;

  const response = await fetchWithRetry("https://www.strava.com/oauth/token", {}, "Strava token refresh", {
    retryCloudFrontBlocks: true,
    retryDelaysMs: [0],
    delayFn: async () => {},
    fetchFn: async () => {
      calls += 1;
      if (calls === 1) {
        return new Response(cloudFrontBlockHtml, {
          status: 403,
          headers: { "Content-Type": "text/html" },
        });
      }

      return jsonResponse({ ok: true }, { status: 200 });
    },
  });

  assert.equal(calls, 2);
  assert.equal(response.status, 200);
});

test("plain 403 responses are not retried", async () => {
  let calls = 0;

  const response = await fetchWithRetry("https://www.strava.com/oauth/token", {}, "Strava token refresh", {
    retryCloudFrontBlocks: true,
    retryDelaysMs: [0],
    delayFn: async () => {},
    fetchFn: async () => {
      calls += 1;
      return jsonResponse({ message: "Forbidden" }, { status: 403 });
    },
  });

  assert.equal(calls, 1);
  assert.equal(response.status, 403);
});

test("400 and 401 token responses fail fast", async () => {
  for (const status of [400, 401]) {
    const reason = await retryReasonForResponse(jsonResponse({ message: "auth error" }, { status }), {
      retryCloudFrontBlocks: true,
    });

    assert.equal(reason, "");
  }
});

test("existing retryable statuses still retry", async () => {
  let calls = 0;

  const response = await fetchWithRetry("https://www.strava.com/api/v3/athlete/activities", {}, "Strava activity fetch", {
    retryDelaysMs: [0],
    delayFn: async () => {},
    fetchFn: async () => {
      calls += 1;
      return calls === 1 ? jsonResponse({ message: "Bad gateway" }, { status: 502 }) : jsonResponse([], { status: 200 });
    },
  });

  assert.equal(calls, 2);
  assert.equal(response.status, 200);
});

test("refreshAccessToken sends form-encoded OAuth parameters", async () => {
  const previousEnv = {
    STRAVA_CLIENT_ID: process.env.STRAVA_CLIENT_ID,
    STRAVA_CLIENT_SECRET: process.env.STRAVA_CLIENT_SECRET,
    STRAVA_REFRESH_TOKEN: process.env.STRAVA_REFRESH_TOKEN,
  };
  process.env.STRAVA_CLIENT_ID = "123";
  process.env.STRAVA_CLIENT_SECRET = "secret";
  process.env.STRAVA_REFRESH_TOKEN = "refresh";

  let requestOptions;
  try {
    const tokens = await refreshAccessToken({
      delayFn: async () => {},
      fetchFn: async (_url, options) => {
        requestOptions = options;
        return jsonResponse({ access_token: "access", refresh_token: "refresh" }, { status: 200 });
      },
    });

    assert.equal(tokens.access_token, "access");
    assert.equal(requestOptions.headers["Content-Type"], "application/x-www-form-urlencoded");

    const body = new URLSearchParams(String(requestOptions.body));
    assert.equal(body.get("client_id"), "123");
    assert.equal(body.get("client_secret"), "secret");
    assert.equal(body.get("refresh_token"), "refresh");
    assert.equal(body.get("grant_type"), "refresh_token");
  } finally {
    for (const [key, value] of Object.entries(previousEnv)) {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    }
  }
});

test("long error bodies are trimmed for final messages", () => {
  const text = "x".repeat(800);
  const trimmed = truncateText(text, 20);

  assert.equal(trimmed, "x".repeat(20) + "... [truncated 780 chars]");
});
